# Generated by Django 4.2 on 2026-05-15 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('venue_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('seminar_room', 'Seminar Room'), ('lab', 'Lab'), ('event_center', 'Event Center'), ('conference_room', 'Conference Room'), ('sports_hall', 'Sports Hall'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('facilities', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'venues',
                'ordering': ['name'],
            },
        ),
    ]
